### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Felli** [GreenMeteor/humhub-timeline-theme#1]
The following is a roadmap for the creation of this theme.

- [ ] Generate basic theme template
- [ ] Overwrite views for Profile & Stream layouts
- [ ] Compile CSS & LESS files
- [ ] Implement a vertical timeline stream for all posts.
